"""add cascade delete to project users

Revision ID: 4824a26cea97
Revises: 883b0207ca73
Create Date: 2026-09-16 23:42:30.695876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4824a26cea97'
down_revision: Union[str, Sequence[str], None] = '883b0207ca73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_users_project_id_fkey'), 'project_users', type_='foreignkey')
    op.create_foreign_key(None, 'project_users', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.create_foreign_key(op.f('project_users_project_id_fkey'), 'project_users', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
