"""add system role to user

Revision ID: 54dd7b8112e3
Revises: 6cc0734fc3cb
Create Date: 2026-09-23 19:22:58.370248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dd7b8112e3'
down_revision: Union[str, Sequence[str], None] = '6cc0734fc3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_users_user_id_fkey'), 'project_users', type_='foreignkey')
    op.create_foreign_key(None, 'project_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_test_suites_project_name'), 'test_suites', type_='unique')
    op.create_unique_constraint(None, 'test_suites', ['name'])
    op.add_column('users', sa.Column('system_role', sa.String(length=30), nullable=False, server_default="USER"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'system_role')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'test_suites', type_='unique')
    op.create_unique_constraint(op.f('uq_test_suites_project_name'), 'test_suites', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.create_foreign_key(op.f('project_users_user_id_fkey'), 'project_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
