"""move role from project membership to user

Revision ID: 775b358ab05d
Revises: 54dd7b8112e3
Create Date: 2026-09-24 21:04:28.644944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775b358ab05d'
down_revision: Union[str, Sequence[str], None] = '54dd7b8112e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.String(length=30), nullable=True))
    op.execute(
        """
        UPDATE users
        SET user_role = (
            SELECT pu.role
            FROM project_users pu
            WHERE pu.user_id = users.id
            ORDER BY
                CASE pu.role
                    WHEN 'ADMIN' THEN 1
                    WHEN 'QA_ENGINEER' THEN 2
                    WHEN 'DEVELOPER' THEN 3
                    WHEN 'VIEWER' THEN 4
                    ELSE 5
                END
            LIMIT 1
        )
        """
    )
    op.execute(
        """
        UPDATE users
        SET user_role = 'VIEWER'
        WHERE user_role IS NULL
        """
    )
    op.alter_column("users", "user_role", existing_type=sa.String(length=30), nullable=False)
    op.drop_column('project_users', 'role')
    op.drop_column('users', 'system_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('system_role', sa.String(length=30), server_default="USER", nullable=False))
    op.execute(
        """
        UPDATE project_users pu
        SET role = u.user_role
        FROM users u
        WHERE u.id = pu.user_id
        """
    )
    op.alter_column(
        "project_users",
        "role",
        existing_type=sa.String(length=30),
        nullable=False,
    )
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
