"""add outbox processing timestamp

Revision ID: 7ddb69468486
Revises: 6086c10d6a65
Create Date: 2026-10-09 17:32:20.393573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddb69468486'
down_revision: Union[str, Sequence[str], None] = '6086c10d6a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'processing_started_at')
    # ### end Alembic commands ###
