"""add execution timeouts to projects module

Revision ID: 88152b566b2d
Revises: 92962cec8635
Create Date: 2026-09-15 01:06:49.820533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88152b566b2d'
down_revision: Union[str, Sequence[str], None] = '92962cec8635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('execution_timeout', sa.Integer(), nullable=False, server_default="3000"))
    op.drop_constraint(op.f('uq_projects_name'), 'projects', type_='unique')
    op.drop_index(op.f('idx_test_cases_project_id'), table_name='test_case')
    op.drop_constraint(op.f('uq_test_case_name'), 'test_case', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_test_case_name'), 'test_case', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_test_cases_project_id'), 'test_case', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('uq_projects_name'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'execution_timeout')
    # ### end Alembic commands ###
