"""add cascase delete to testase

Revision ID: 883b0207ca73
Revises: b9f6099e9a6d
Create Date: 2026-09-16 21:21:48.551778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883b0207ca73'
down_revision: Union[str, Sequence[str], None] = 'b9f6099e9a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_case_project'), 'test_case', type_='foreignkey')
    op.create_foreign_key(None, 'test_case', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_case_project'), 'test_case', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
