"""
baseline
Revision ID: 92962cec8635
Revises: 
Create Date: 2026-09-15 00:44:44.165975
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92962cec8635'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_name'), 'projects', type_='unique')
    op.drop_index(op.f('idx_test_cases_project_id'), table_name='test_case')
    op.drop_constraint(op.f('uq_test_case_name'), 'test_case', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_test_case_name'), 'test_case', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_test_cases_project_id'), 'test_case', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('uq_projects_name'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###