from enum import Enum

class Permission(str, Enum):
    PROJECT_VIEW = "PROJECT_VIEW"
    PROJECT_CREATE = "PROJECT_CREATE"
    PROJECT_UPDATE = "PROJECT_UPDATE"
    PROJECT_DELETE = "PROJECT_DELETE"

    MEMBER_VIEW = "MEMBER_VIEW"
    MEMBER_MANANGE = "MEMBER_MANAGE"

    TEST_SUITE_VIEW = "TEST_SUITE_VIEW"
    TEST_SUITE_CREATE = "TEST_SUITE_CREATE"
    TEST_SUITE_UPDATE = "TEST_SUITE_UPDATE"
    TEST_SUITE_DELETE = "TEST_SUITE_DELETE"
    
    TEST_CASE_VIEW = "TEST_CASE_VIEW"
    TEST_CASE_CREATE = "TEST_CASE_CREATE"
    TEST_CASE_UPDATE = "TEST_CASE_UPDATE"
    TEST_CASE_DELETE = "TEST_CASE_DELETE"
    TEST_CASE_EXECUTE = "TEST_CASE_EXECUTE"